### ISSUE TITLE
Doesn't work with Bolt 2.0

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/boltwash#12]
With the Bolt 2.0 gem installed, boltwash errors trying to list a filesystem with
```
NoMethodError: undefined method `targets' for #<Hash:0x00007fbc3d928ed8>
  /Users/michaelsmith/puppetlabs/boltwash/.bundle/gems/ruby/2.6.0/gems/bolt-2.0.1/lib/bolt/target.rb:104:in `inventory_target'
  /Users/michaelsmith/puppetlabs/boltwash/.bundle/gems/ruby/2.6.0/gems/bolt-2.0.1/lib/bolt/target.rb:126:in `transport'
  /Users/michaelsmith/puppetlabs/boltwash/bolt.rb:162:in `exec'
  /Users/michaelsmith/puppetlabs/boltwash/.bundle/gems/ruby/2.6.0/gems/wash-0.4.1/lib/wash/method.rb:61:in `block in <module:Method>'
  /Users/michaelsmith/puppetlabs/boltwash/.bundle/gems/ruby/2.6.0/gems/wash-0.4.1/lib/wash/method.rb:14:in `invoke'
  /Users/michaelsmith/puppetlabs/boltwash/.bundle/gems/ruby/2.6.0/gems/wash-0.4.1/lib/wash.rb:90:in `run'
  /Users/michaelsmith/puppetlabs/boltwash/bolt.rb:198:in `<top (required)>'
```
